---
config:
  theme: 'base'
  themeVariables:
    primaryColor: '#eaf6e0'
    secondaryColor: '#eaf6e0'
    background: white
---

flowchart LR
    START --> needs_research -.no .-> writer --> END
    needs_research -.yes.->agent
    agent-->tool_calls
    tool_calls -.yes.-> tools --> agent
    tool_calls -.no .-> writer
    needs_research{needs
    research?}
    tool_calls{has tool
    calls?}

    subgraph REACT AGENT
        agent
        tool_calls
        tools
    end

    classDef node fill:#fff,stroke:#444,stroke-width:2px,color:#222;
    classDef cluster fill:#eaf6e0,stroke:#76b900,stroke-width:3px,color:#111,rounded corners,shadow;