---
config:
  theme: 'base'
  themeVariables:
    primaryColor: '#eaf6e0'
    secondaryColor: '#eaf6e0'
    background: white
---

flowchart LR

    Prompt --> LLM

    subgraph agent[ReAct Agent]
        direction LR
        LLM  --> has_tools{has tool<br />calls?} -.yes.-> tools --> LLM
    end

    tools ==tool call==> retrieval

    subgraph retrieval[Retrieval Chain]
        embedding[Embedding<br />Model] -->
        vector_search[(Vector DB<br />Search)] -->
        rerank[Reranking<br />Model]
    end

    has_tools -.no .-> Response

    classDef node fill:#fff,stroke:#444,stroke-width:2px,color:#222;
    classDef cluster fill:#eaf6e0,stroke:#76b900,stroke-width:3px,color:#111,rounded corners,shadow;