---
config:
  theme: 'base'
  themeVariables:
    primaryColor: '#eaf6e0'
    secondaryColor: '#eaf6e0'
    background: white
---

flowchart LR
    START(["START"]):::node --> agent(["agent"]):::node --> tool_calls(["tool_calls"]):::node
    tool_calls -.yes.-> tools(["tools"]):::node --> agent
    tool_calls -.no ..-> END(["END"]):::node
    tool_calls{{"has tool<br>calls?"}}:::node

    subgraph REACT_AGENT["REACT AGENT"]
        agent
        tool_calls
        tools
    end

    classDef node fill:#fff,stroke:#444,stroke-width:2px,color:#222;
    classDef cluster fill:#eaf6e0,stroke:#76b900,stroke-width:3px,color:#111,rounded corners,shadow;